_dinfo_keybase_build_secrets: >-
  {{ lookup("file", "/keybase/team/epfl_si.build_common/build-secrets.yml") |
  from_yaml }}

dinfo_build_c4science_credentials: >-
  {{ _dinfo_keybase_build_secrets.c4science_clone_credentials }}

dinfo_perl_base_image_name: perl-base
dinfo_build_openshift_namespace: '{{ inventory_hostname }}'
