dinfo_build_keybase_dir: "/keybase/team/epfl_si.build_common"

_dinfo_keybase_build_secrets: >-
  {{ lookup("file", "{{ dinfo_build_keybase_dir }}/build-secrets.yml") |
  from_yaml }}

dinfo_build_c4science_credentials: >-
  {{ _dinfo_keybase_build_secrets.c4science_clone_credentials }}

dinfo_perl_base_image_name: cadi-libs-idevfsd
dinfo_build_openshift_namespace: '{{ inventory_hostname }}'
dinfo_build_cadi_libs_git_repository: ssh://git@c4science.ch/diffusion/1989/cadi-libs.git
dinfo_build_cadi_libs_ssh_secret_key_path: "{{ dinfo_build_keybase_dir }}/id_rsa_c4science_idevfsd-checkouter"
dinfo_build_cadi_libs_ssh_known_hosts_cmd: "ssh-keyscan c4science.ch"
